actors:
  ida_10:
    image_url: /images/actors/ida_10.png
    name: ida_10
    url: https://twitter.com/IDA_10
  miyaoka:
    image_url: /images/actors/miyaoka.png
    name: miyaoka
    url: https://twitter.com/miyaoka
author: "@IDA_10 x @miyaoka"
description: 日米のゲーム文化を話すPodcast
description_long: サンフランシスコのゲーム会社で働くイダテンと、東京のゲーム好きのみやおかが、日米のゲームや文化などを話していくPodcast
email:
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
hashtag: picocas
itunes_podcast_url:
keywords: game, picocas
language: ja
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: "@IDA_10 x @miyaokaのピコピコキャスト"
title_short: "ピコピコキャスト"
url: https://picocas.github.io